hico_verb_object_list = [('board', 'airplane'),
 ('direct', 'airplane'),
 ('exit', 'airplane'),
 ('fly', 'airplane'),
 ('inspect', 'airplane'),
 ('load', 'airplane'),
 ('ride', 'airplane'),
 ('sit on', 'airplane'),
 ('wash', 'airplane'),
 ('no interaction', 'airplane'),
 ('carry', 'bicycle'),
 ('hold', 'bicycle'),
 ('inspect', 'bicycle'),
 ('jump', 'bicycle'),
 ('hop on', 'bicycle'),
 ('park', 'bicycle'),
 ('push', 'bicycle'),
 ('repair', 'bicycle'),
 ('ride', 'bicycle'),
 ('sit on', 'bicycle'),
 ('straddle', 'bicycle'),
 ('walk', 'bicycle'),
 ('wash', 'bicycle'),
 ('no interaction', 'bicycle'),
 ('chase', 'bird'),
 ('feed', 'bird'),
 ('hold', 'bird'),
 ('pet', 'bird'),
 ('release', 'bird'),
 ('watch', 'bird'),
 ('no interaction', 'bird'),
 ('board', 'boat'),
 ('drive', 'boat'),
 ('exit', 'boat'),
 ('inspect', 'boat'),
 ('jump', 'boat'),
 ('launch', 'boat'),
 ('repair', 'boat'),
 ('ride', 'boat'),
 ('row', 'boat'),
 ('sail', 'boat'),
 ('sit on', 'boat'),
 ('stand on', 'boat'),
 ('tie', 'boat'),
 ('wash', 'boat'),
 ('no interaction', 'boat'),
 ('carry', 'bottle'),
 ('drink with', 'bottle'),
 ('hold', 'bottle'),
 ('inspect', 'bottle'),
 ('lick', 'bottle'),
 ('open', 'bottle'),
 ('pour', 'bottle'),
 ('no interaction', 'bottle'),
 ('board', 'bus'),
 ('direct', 'bus'),
 ('drive', 'bus'),
 ('exit', 'bus'),
 ('inspect', 'bus'),
 ('load', 'bus'),
 ('ride', 'bus'),
 ('sit on', 'bus'),
 ('wash', 'bus'),
 ('wave', 'bus'),
 ('no interaction', 'bus'),
 ('board', 'car'),
 ('direct', 'car'),
 ('drive', 'car'),
 ('hose', 'car'),
 ('inspect', 'car'),
 ('jump', 'car'),
 ('load', 'car'),
 ('park', 'car'),
 ('ride', 'car'),
 ('wash', 'car'),
 ('no interaction', 'car'),
 ('dry', 'cat'),
 ('feed', 'cat'),
 ('hold', 'cat'),
 ('hug', 'cat'),
 ('kiss', 'cat'),
 ('pet', 'cat'),
 ('scratch', 'cat'),
 ('wash', 'cat'),
 ('chase', 'cat'),
 ('no interaction', 'cat'),
 ('carry', 'chair'),
 ('hold', 'chair'),
 ('lie on', 'chair'),
 ('sit on', 'chair'),
 ('stand on', 'chair'),
 ('no interaction', 'chair'),
 ('carry', 'couch'),
 ('lie on', 'couch'),
 ('sit on', 'couch'),
 ('no interaction', 'couch'),
 ('feed', 'cow'),
 ('herd', 'cow'),
 ('hold', 'cow'),
 ('hug', 'cow'),
 ('kiss', 'cow'),
 ('lasso', 'cow'),
 ('milk', 'cow'),
 ('pet', 'cow'),
 ('ride', 'cow'),
 ('walk', 'cow'),
 ('no interaction', 'cow'),
 ('clean', 'dining table'),
 ('eat at', 'dining table'),
 ('sit at', 'dining table'),
 ('no interaction', 'dining table'),
 ('carry', 'dog'),
 ('dry', 'dog'),
 ('feed', 'dog'),
 ('groom', 'dog'),
 ('hold', 'dog'),
 ('hose', 'dog'),
 ('hug', 'dog'),
 ('inspect', 'dog'),
 ('kiss', 'dog'),
 ('pet', 'dog'),
 ('run', 'dog'),
 ('scratch', 'dog'),
 ('straddle', 'dog'),
 ('train', 'dog'),
 ('walk', 'dog'),
 ('wash', 'dog'),
 ('chase', 'dog'),
 ('no interaction', 'dog'),
 ('feed', 'horse'),
 ('groom', 'horse'),
 ('hold', 'horse'),
 ('hug', 'horse'),
 ('jump', 'horse'),
 ('kiss', 'horse'),
 ('load', 'horse'),
 ('hop on', 'horse'),
 ('pet', 'horse'),
 ('race', 'horse'),
 ('ride', 'horse'),
 ('run', 'horse'),
 ('straddle', 'horse'),
 ('train', 'horse'),
 ('walk', 'horse'),
 ('wash', 'horse'),
 ('no interaction', 'horse'),
 ('hold', 'motorcycle'),
 ('inspect', 'motorcycle'),
 ('jump', 'motorcycle'),
 ('hop on', 'motorcycle'),
 ('park', 'motorcycle'),
 ('push', 'motorcycle'),
 ('race', 'motorcycle'),
 ('ride', 'motorcycle'),
 ('sit on', 'motorcycle'),
 ('straddle', 'motorcycle'),
 ('turn', 'motorcycle'),
 ('walk', 'motorcycle'),
 ('wash', 'motorcycle'),
 ('no interaction', 'motorcycle'),
 ('carry', 'person'),
 ('greet', 'person'),
 ('hold', 'person'),
 ('hug', 'person'),
 ('kiss', 'person'),
 ('stab', 'person'),
 ('tag', 'person'),
 ('teach', 'person'),
 ('lick', 'person'),
 ('no interaction', 'person'),
 ('carry', 'potted plant'),
 ('hold', 'potted plant'),
 ('hose', 'potted plant'),
 ('no interaction', 'potted plant'),
 ('carry', 'sheep'),
 ('feed', 'sheep'),
 ('herd', 'sheep'),
 ('hold', 'sheep'),
 ('hug', 'sheep'),
 ('kiss', 'sheep'),
 ('pet', 'sheep'),
 ('ride', 'sheep'),
 ('shear', 'sheep'),
 ('walk', 'sheep'),
 ('wash', 'sheep'),
 ('no interaction', 'sheep'),
 ('board', 'train'),
 ('drive', 'train'),
 ('exit', 'train'),
 ('load', 'train'),
 ('ride', 'train'),
 ('sit on', 'train'),
 ('wash', 'train'),
 ('no interaction', 'train'),
 ('control', 'tv'),
 ('repair', 'tv'),
 ('watch', 'tv'),
 ('no interaction', 'tv'),
 ('buy', 'apple'),
 ('cut', 'apple'),
 ('eat', 'apple'),
 ('hold', 'apple'),
 ('inspect', 'apple'),
 ('peel', 'apple'),
 ('pick', 'apple'),
 ('smell', 'apple'),
 ('wash', 'apple'),
 ('no interaction', 'apple'),
 ('carry', 'backpack'),
 ('hold', 'backpack'),
 ('inspect', 'backpack'),
 ('open', 'backpack'),
 ('wear', 'backpack'),
 ('no interaction', 'backpack'),
 ('buy', 'banana'),
 ('carry', 'banana'),
 ('cut', 'banana'),
 ('eat', 'banana'),
 ('hold', 'banana'),
 ('inspect', 'banana'),
 ('peel', 'banana'),
 ('pick', 'banana'),
 ('smell', 'banana'),
 ('no interaction', 'banana'),
 ('break', 'baseball bat'),
 ('carry', 'baseball bat'),
 ('hold', 'baseball bat'),
 ('sign', 'baseball bat'),
 ('swing', 'baseball bat'),
 ('throw', 'baseball bat'),
 ('wield', 'baseball bat'),
 ('no interaction', 'baseball bat'),
 ('hold', 'baseball glove'),
 ('wear', 'baseball glove'),
 ('no interaction', 'baseball glove'),
 ('feed', 'bear'),
 ('hunt', 'bear'),
 ('watch', 'bear'),
 ('no interaction', 'bear'),
 ('clean', 'bed'),
 ('lie on', 'bed'),
 ('sit on', 'bed'),
 ('no interaction', 'bed'),
 ('inspect', 'bench'),
 ('lie on', 'bench'),
 ('sit on', 'bench'),
 ('no interaction', 'bench'),
 ('carry', 'book'),
 ('hold', 'book'),
 ('open', 'book'),
 ('read', 'book'),
 ('no interaction', 'book'),
 ('hold', 'bowl'),
 ('stir', 'bowl'),
 ('wash', 'bowl'),
 ('lick', 'bowl'),
 ('no interaction', 'bowl'),
 ('cut', 'broccoli'),
 ('eat', 'broccoli'),
 ('hold', 'broccoli'),
 ('smell', 'broccoli'),
 ('stir', 'broccoli'),
 ('wash', 'broccoli'),
 ('no interaction', 'broccoli'),
 ('blow', 'cake'),
 ('carry', 'cake'),
 ('cut', 'cake'),
 ('eat', 'cake'),
 ('hold', 'cake'),
 ('light', 'cake'),
 ('make', 'cake'),
 ('pick up', 'cake'),
 ('no interaction', 'cake'),
 ('carry', 'carrot'),
 ('cook', 'carrot'),
 ('cut', 'carrot'),
 ('eat', 'carrot'),
 ('hold', 'carrot'),
 ('peel', 'carrot'),
 ('smell', 'carrot'),
 ('stir', 'carrot'),
 ('wash', 'carrot'),
 ('no interaction', 'carrot'),
 ('carry', 'cell phone'),
 ('hold', 'cell phone'),
 ('read', 'cell phone'),
 ('repair', 'cell phone'),
 ('talk on', 'cell phone'),
 ('text on', 'cell phone'),
 ('no interaction', 'cell phone'),
 ('check', 'clock'),
 ('hold', 'clock'),
 ('repair', 'clock'),
 ('set', 'clock'),
 ('no interaction', 'clock'),
 ('carry', 'cup'),
 ('drink with', 'cup'),
 ('hold', 'cup'),
 ('inspect', 'cup'),
 ('pour', 'cup'),
 ('sip', 'cup'),
 ('smell', 'cup'),
 ('fill', 'cup'),
 ('wash', 'cup'),
 ('no interaction', 'cup'),
 ('buy', 'donut'),
 ('carry', 'donut'),
 ('eat', 'donut'),
 ('hold', 'donut'),
 ('make', 'donut'),
 ('pick up', 'donut'),
 ('smell', 'donut'),
 ('no interaction', 'donut'),
 ('feed', 'elephant'),
 ('hold', 'elephant'),
 ('hose', 'elephant'),
 ('hug', 'elephant'),
 ('kiss', 'elephant'),
 ('hop on', 'elephant'),
 ('pet', 'elephant'),
 ('ride', 'elephant'),
 ('walk', 'elephant'),
 ('wash', 'elephant'),
 ('watch', 'elephant'),
 ('no interaction', 'elephant'),
 ('hug', 'fire hydrant'),
 ('inspect', 'fire hydrant'),
 ('open', 'fire hydrant'),
 ('paint', 'fire hydrant'),
 ('no interaction', 'fire hydrant'),
 ('hold', 'fork'),
 ('lift', 'fork'),
 ('stick', 'fork'),
 ('lick', 'fork'),
 ('wash', 'fork'),
 ('no interaction', 'fork'),
 ('block', 'frisbee'),
 ('catch', 'frisbee'),
 ('hold', 'frisbee'),
 ('spin', 'frisbee'),
 ('throw', 'frisbee'),
 ('no interaction', 'frisbee'),
 ('feed', 'giraffe'),
 ('kiss', 'giraffe'),
 ('pet', 'giraffe'),
 ('ride', 'giraffe'),
 ('watch', 'giraffe'),
 ('no interaction', 'giraffe'),
 ('hold', 'hair drier'),
 ('operate', 'hair drier'),
 ('repair', 'hair drier'),
 ('no interaction', 'hair drier'),
 ('carry', 'handbag'),
 ('hold', 'handbag'),
 ('inspect', 'handbag'),
 ('no interaction', 'handbag'),
 ('carry', 'hot dog'),
 ('cook', 'hot dog'),
 ('cut', 'hot dog'),
 ('eat', 'hot dog'),
 ('hold', 'hot dog'),
 ('make', 'hot dog'),
 ('no interaction', 'hot dog'),
 ('carry', 'keyboard'),
 ('clean', 'keyboard'),
 ('hold', 'keyboard'),
 ('type on', 'keyboard'),
 ('no interaction', 'keyboard'),
 ('assemble', 'kite'),
 ('carry', 'kite'),
 ('fly', 'kite'),
 ('hold', 'kite'),
 ('inspect', 'kite'),
 ('launch', 'kite'),
 ('pull', 'kite'),
 ('no interaction', 'kite'),
 ('cut with', 'knife'),
 ('hold', 'knife'),
 ('stick', 'knife'),
 ('wash', 'knife'),
 ('wield', 'knife'),
 ('lick', 'knife'),
 ('no interaction', 'knife'),
 ('hold', 'laptop'),
 ('open', 'laptop'),
 ('read', 'laptop'),
 ('repair', 'laptop'),
 ('type on', 'laptop'),
 ('no interaction', 'laptop'),
 ('clean', 'microwave'),
 ('open', 'microwave'),
 ('operate', 'microwave'),
 ('no interaction', 'microwave'),
 ('control', 'mouse'),
 ('hold', 'mouse'),
 ('repair', 'mouse'),
 ('no interaction', 'mouse'),
 ('buy', 'orange'),
 ('cut', 'orange'),
 ('eat', 'orange'),
 ('hold', 'orange'),
 ('inspect', 'orange'),
 ('peel', 'orange'),
 ('pick', 'orange'),
 ('squeeze', 'orange'),
 ('wash', 'orange'),
 ('no interaction', 'orange'),
 ('clean', 'oven'),
 ('hold', 'oven'),
 ('inspect', 'oven'),
 ('open', 'oven'),
 ('repair', 'oven'),
 ('operate', 'oven'),
 ('no interaction', 'oven'),
 ('check', 'parking meter'),
 ('pay', 'parking meter'),
 ('repair', 'parking meter'),
 ('no interaction', 'parking meter'),
 ('buy', 'pizza'),
 ('carry', 'pizza'),
 ('cook', 'pizza'),
 ('cut', 'pizza'),
 ('eat', 'pizza'),
 ('hold', 'pizza'),
 ('make', 'pizza'),
 ('pick up', 'pizza'),
 ('slide', 'pizza'),
 ('smell', 'pizza'),
 ('no interaction', 'pizza'),
 ('clean', 'refrigerator'),
 ('hold', 'refrigerator'),
 ('move', 'refrigerator'),
 ('open', 'refrigerator'),
 ('no interaction', 'refrigerator'),
 ('hold', 'remote'),
 ('point', 'remote'),
 ('swing', 'remote'),
 ('no interaction', 'remote'),
 ('carry', 'sandwich'),
 ('cook', 'sandwich'),
 ('cut', 'sandwich'),
 ('eat', 'sandwich'),
 ('hold', 'sandwich'),
 ('make', 'sandwich'),
 ('no interaction', 'sandwich'),
 ('cut with', 'scissors'),
 ('hold', 'scissors'),
 ('open', 'scissors'),
 ('no interaction', 'scissors'),
 ('clean', 'sink'),
 ('repair', 'sink'),
 ('wash', 'sink'),
 ('no interaction', 'sink'),
 ('carry', 'skateboard'),
 ('flip', 'skateboard'),
 ('grind', 'skateboard'),
 ('hold', 'skateboard'),
 ('jump', 'skateboard'),
 ('pick up', 'skateboard'),
 ('ride', 'skateboard'),
 ('sit on', 'skateboard'),
 ('stand on', 'skateboard'),
 ('no interaction', 'skateboard'),
 ('adjust', 'skis'),
 ('carry', 'skis'),
 ('hold', 'skis'),
 ('inspect', 'skis'),
 ('jump', 'skis'),
 ('pick up', 'skis'),
 ('repair', 'skis'),
 ('ride', 'skis'),
 ('stand on', 'skis'),
 ('wear', 'skis'),
 ('no interaction', 'skis'),
 ('adjust', 'snowboard'),
 ('carry', 'snowboard'),
 ('grind', 'snowboard'),
 ('hold', 'snowboard'),
 ('jump', 'snowboard'),
 ('ride', 'snowboard'),
 ('stand on', 'snowboard'),
 ('wear', 'snowboard'),
 ('no interaction', 'snowboard'),
 ('hold', 'spoon'),
 ('lick', 'spoon'),
 ('wash', 'spoon'),
 ('sip', 'spoon'),
 ('no interaction', 'spoon'),
 ('block', 'sports ball'),
 ('carry', 'sports ball'),
 ('catch', 'sports ball'),
 ('dribble', 'sports ball'),
 ('hit', 'sports ball'),
 ('hold', 'sports ball'),
 ('inspect', 'sports ball'),
 ('kick', 'sports ball'),
 ('pick up', 'sports ball'),
 ('serve', 'sports ball'),
 ('sign', 'sports ball'),
 ('spin', 'sports ball'),
 ('throw', 'sports ball'),
 ('no interaction', 'sports ball'),
 ('hold', 'stop sign'),
 ('stand under', 'stop sign'),
 ('stop at', 'stop sign'),
 ('no interaction', 'stop sign'),
 ('carry', 'suitcase'),
 ('drag', 'suitcase'),
 ('hold', 'suitcase'),
 ('hug', 'suitcase'),
 ('load', 'suitcase'),
 ('open', 'suitcase'),
 ('pack', 'suitcase'),
 ('pick up', 'suitcase'),
 ('zip', 'suitcase'),
 ('no interaction', 'suitcase'),
 ('carry', 'surfboard'),
 ('drag', 'surfboard'),
 ('hold', 'surfboard'),
 ('inspect', 'surfboard'),
 ('jump', 'surfboard'),
 ('lie on', 'surfboard'),
 ('load', 'surfboard'),
 ('ride', 'surfboard'),
 ('stand on', 'surfboard'),
 ('sit on', 'surfboard'),
 ('wash', 'surfboard'),
 ('no interaction', 'surfboard'),
 ('carry', 'teddy bear'),
 ('hold', 'teddy bear'),
 ('hug', 'teddy bear'),
 ('kiss', 'teddy bear'),
 ('no interaction', 'teddy bear'),
 ('carry', 'tennis racket'),
 ('hold', 'tennis racket'),
 ('inspect', 'tennis racket'),
 ('swing', 'tennis racket'),
 ('no interaction', 'tennis racket'),
 ('adjust', 'tie'),
 ('cut', 'tie'),
 ('hold', 'tie'),
 ('inspect', 'tie'),
 ('pull', 'tie'),
 ('tie', 'tie'),
 ('wear', 'tie'),
 ('no interaction', 'tie'),
 ('hold', 'toaster'),
 ('operate', 'toaster'),
 ('repair', 'toaster'),
 ('no interaction', 'toaster'),
 ('clean', 'toilet'),
 ('flush', 'toilet'),
 ('open', 'toilet'),
 ('repair', 'toilet'),
 ('sit on', 'toilet'),
 ('stand on', 'toilet'),
 ('wash', 'toilet'),
 ('no interaction', 'toilet'),
 ('brush with', 'toothbrush'),
 ('hold', 'toothbrush'),
 ('wash', 'toothbrush'),
 ('no interaction', 'toothbrush'),
 ('install', 'traffic light'),
 ('repair', 'traffic light'),
 ('stand under', 'traffic light'),
 ('stop at', 'traffic light'),
 ('no interaction', 'traffic light'),
 ('direct', 'truck'),
 ('drive', 'truck'),
 ('inspect', 'truck'),
 ('load', 'truck'),
 ('repair', 'truck'),
 ('ride', 'truck'),
 ('sit on', 'truck'),
 ('wash', 'truck'),
 ('no interaction', 'truck'),
 ('carry', 'umbrella'),
 ('hold', 'umbrella'),
 ('lose', 'umbrella'),
 ('open', 'umbrella'),
 ('repair', 'umbrella'),
 ('set', 'umbrella'),
 ('stand under', 'umbrella'),
 ('no interaction', 'umbrella'),
 ('hold', 'vase'),
 ('make', 'vase'),
 ('paint', 'vase'),
 ('no interaction', 'vase'),
 ('fill', 'wine glass'),
 ('hold', 'wine glass'),
 ('sip', 'wine glass'),
 ('toast', 'wine glass'),
 ('lick', 'wine glass'),
 ('wash', 'wine glass'),
 ('no interaction', 'wine glass'),
 ('feed', 'zebra'),
 ('hold', 'zebra'),
 ('pet', 'zebra'),
 ('watch', 'zebra'),
 ('no interaction', 'zebra')]

hico_verbs = ['adjust', 'assemble', 'block', 'blow', 'board', 'break', 'brush with', 'buy', 'carry', 'catch',
 'chase', 'check', 'clean', 'control', 'cook', 'cut', 'cut with', 'direct', 'drag', 'dribble',
 'drink with', 'drive', 'dry', 'eat', 'eat at', 'exit', 'feed', 'fill', 'flip', 'flush',
 'fly', 'greet', 'grind', 'groom', 'herd', 'hit', 'hold', 'hop on', 'hose', 'hug',
 'hunt', 'inspect', 'install', 'jump', 'kick', 'kiss', 'lasso', 'launch', 'lick', 'lie on', 
 'lift', 'light', 'load', 'lose', 'make', 'milk', 'move', 'no interaction', 'open', 'operate',
 'pack', 'paint', 'park', 'pay', 'peel', 'pet', 'pick', 'pick up', 'point', 'pour', 
 'pull', 'push', 'race', 'read', 'release', 'repair', 'ride', 'row', 'run', 'sail', 
 'scratch', 'serve', 'set', 'shear', 'sign', 'sip', 'sit at', 'sit on', 'slide', 'smell', 
 'spin', 'squeeze', 'stab', 'stand on', 'stand under', 'stick', 'stir', 'stop at', 'straddle', 'swing', 
 'tag', 'talk on', 'teach', 'text on', 'throw', 'tie', 'toast', 'train', 'turn', 'type on', 
 'walk', 'wash', 'watch', 'wave', 'wear', 'wield', 'zip']
 
hico_objects = ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic_light', 
'fire_hydrant', 'stop_sign', 'parking_meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 
'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports_ball', 
'kite', 'baseball_bat', 'baseball_glove', 'skateboard', 'surfboard', 'tennis_racket', 'bottle', 'wine_glass', 'cup', 'fork',
'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot_dog', 'pizza', 'donut', 'cake', 
'chair', 'couch', 'potted_plant', 'bed', 'dining_table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell_phone',
'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy_bear', 'hair_drier', 'toothbrush']

hico_verbs_sentence = ['a photo of a person is adjusting the object',
 'a photo of a person is assembling the object',
 'a photo of a person is blocking the object',
 'a photo of a person is blowing the object',
 'a photo of a person is boarding the object',
 'a photo of a person is breaking the object',
 'a photo of a person is brushing with the object',
 'a photo of a person is buying the object',
 'a photo of a person is carrying the object',
 'a photo of a person is catching the object',
 'a photo of a person is chasing the object',
 'a photo of a person is checking the object',
 'a photo of a person is cleaning the object',
 'a photo of a person is controling the object',
 'a photo of a person is cooking the object',
 'a photo of a person is cutting the object',
 'a photo of a person is cutting with the object',
 'a photo of a person is directing the object',
 'a photo of a person is draging the object',
 'a photo of a person is dribbling the object',
 'a photo of a person is drinking with the object',
 'a photo of a person is driving the object',
 'a photo of a person is drying the object',
 'a photo of a person is eating the object',
 'a photo of a person is eating at the object',
 'a photo of a person is exiting the object',
 'a photo of a person is feeding the object',
 'a photo of a person is filling the object',
 'a photo of a person is flipping the object',
 'a photo of a person is flushing the object',
 'a photo of a person is flying the object',
 'a photo of a person is greeting the object',
 'a photo of a person is grinding the object',
 'a photo of a person is grooming the object',
 'a photo of a person is herding the object',
 'a photo of a person is hiting the object',
 'a photo of a person is holding the object',
 'a photo of a person is hopping on the object',
 'a photo of a person is hosing the object',
 'a photo of a person is hugging the object',
 'a photo of a person is hunting the object',
 'a photo of a person is inspecting the object',
 'a photo of a person is installing the object',
 'a photo of a person is jumping the object',
 'a photo of a person is kicking the object',
 'a photo of a person is kissing the object',
 'a photo of a person is lassoing the object',
 'a photo of a person is launching the object',
 'a photo of a person is licking the object',
 'a photo of a person is lying on the object',
 'a photo of a person is lifting the object',
 'a photo of a person is lighting the object',
 'a photo of a person is loading the object',
 'a photo of a person is losing the object',
 'a photo of a person is making the object',
 'a photo of a person is milking the object',
 'a photo of a person is moving the object',
 'a photo of a person and the object with no interaction',
 'a photo of a person is opening the object',
 'a photo of a person is operating the object',
 'a photo of a person is packing the object',
 'a photo of a person is painting the object',
 'a photo of a person is parking the object',
 'a photo of a person is paying the object',
 'a photo of a person is peeling the object',
 'a photo of a person is petting the object',
 'a photo of a person is picking the object',
 'a photo of a person is picking up the object',
 'a photo of a person is pointing the object',
 'a photo of a person is pouring the object',
 'a photo of a person is pulling the object',
 'a photo of a person is pushing the object',
 'a photo of a person is racing the object',
 'a photo of a person is reading the object',
 'a photo of a person is releasing the object',
 'a photo of a person is repairing the object',
 'a photo of a person is riding the object',
 'a photo of a person is rowing the object',
 'a photo of a person is running the object',
 'a photo of a person is sailing the object',
 'a photo of a person is scratching the object',
 'a photo of a person is serving the object',
 'a photo of a person is setting the object',
 'a photo of a person is shearing the object',
 'a photo of a person is signing the object',
 'a photo of a person is siping the object',
 'a photo of a person is sitting at the object',
 'a photo of a person is sitting on the object',
 'a photo of a person is sliding the object',
 'a photo of a person is smelling the object',
 'a photo of a person is spining the object',
 'a photo of a person is squeezing the object',
 'a photo of a person is stabbing the object',
 'a photo of a person is standing on the object',
 'a photo of a person is standing under the object',
 'a photo of a person is sticking the object',
 'a photo of a person is stirring the object',
 'a photo of a person is stopping at the object',
 'a photo of a person is straddling the object',
 'a photo of a person is swinging the object',
 'a photo of a person is tagging the object',
 'a photo of a person is talking on the object',
 'a photo of a person is teaching the object',
 'a photo of a person is texting on the object',
 'a photo of a person is throwing the object',
 'a photo of a person is tying the object',
 'a photo of a person is toasting the object',
 'a photo of a person is training the object',
 'a photo of a person is turning the object',
 'a photo of a person is typing on the object',
 'a photo of a person is walking the object',
 'a photo of a person is washing the object',
 'a photo of a person is watching the object',
 'a photo of a person is waving the object',
 'a photo of a person is wearing the object',
 'a photo of a person is wielding the object',
 'a photo of a person is zipping the object']


hico_verbs_sentence_2=['action of the union region is adjusting',
 'action of the union region is assembling',
 'action of the union region is blocking',
 'action of the union region is blowing',
 'action of the union region is boarding',
 'action of the union region is breaking',
 'action of the union region is brushing with',
 'action of the union region is buying',
 'action of the union region is carrying',
 'action of the union region is catching',
 'action of the union region is chasing',
 'action of the union region is checking',
 'action of the union region is cleaning',
 'action of the union region is controling',
 'action of the union region is cooking',
 'action of the union region is cutting',
 'action of the union region is cutting with',
 'action of the union region is directing',
 'action of the union region is draging',
 'action of the union region is dribbling',
 'action of the union region is drinking with',
 'action of the union region is driving',
 'action of the union region is drying',
 'action of the union region is eating',
 'action of the union region is eating at',
 'action of the union region is exiting',
 'action of the union region is feeding',
 'action of the union region is filling',
 'action of the union region is flipping',
 'action of the union region is flushing',
 'action of the union region is flying',
 'action of the union region is greeting',
 'action of the union region is grinding',
 'action of the union region is grooming',
 'action of the union region is herding',
 'action of the union region is hiting',
 'action of the union region is holding',
 'action of the union region is hopping on',
 'action of the union region is hosing',
 'action of the union region is hugging',
 'action of the union region is hunting',
 'action of the union region is inspecting',
 'action of the union region is installing',
 'action of the union region is jumping',
 'action of the union region is kicking',
 'action of the union region is kissing',
 'action of the union region is lassoing',
 'action of the union region is launching',
 'action of the union region is licking',
 'action of the union region is lying on',
 'action of the union region is lifting',
 'action of the union region is lighting',
 'action of the union region is loading',
 'action of the union region is losing',
 'action of the union region is making',
 'action of the union region is milking',
 'action of the union region is moving',
 'action of the union region is the object with',
 'action of the union region is opening',
 'action of the union region is operating',
 'action of the union region is packing',
 'action of the union region is painting',
 'action of the union region is parking',
 'action of the union region is paying',
 'action of the union region is peeling',
 'action of the union region is petting',
 'action of the union region is picking',
 'action of the union region is picking up',
 'action of the union region is pointing',
 'action of the union region is pouring',
 'action of the union region is pulling',
 'action of the union region is pushing',
 'action of the union region is racing',
 'action of the union region is reading',
 'action of the union region is releasing',
 'action of the union region is repairing',
 'action of the union region is riding',
 'action of the union region is rowing',
 'action of the union region is running',
 'action of the union region is sailing',
 'action of the union region is scratching',
 'action of the union region is serving',
 'action of the union region is setting',
 'action of the union region is shearing',
 'action of the union region is signing',
 'action of the union region is siping',
 'action of the union region is sitting at',
 'action of the union region is sitting on',
 'action of the union region is sliding',
 'action of the union region is smelling',
 'action of the union region is spining',
 'action of the union region is squeezing',
 'action of the union region is stabbing',
 'action of the union region is standing on',
 'action of the union region is standing under',
 'action of the union region is sticking',
 'action of the union region is stirring',
 'action of the union region is stopping at',
 'action of the union region is straddling',
 'action of the union region is swinging',
 'action of the union region is tagging',
 'action of the union region is talking on',
 'action of the union region is teaching',
 'action of the union region is texting on',
 'action of the union region is throwing',
 'action of the union region is tying',
 'action of the union region is toasting',
 'action of the union region is training',
 'action of the union region is turning',
 'action of the union region is typing on',
 'action of the union region is walking',
 'action of the union region is washing',
 'action of the union region is watching',
 'action of the union region is waving',
 'action of the union region is wearing',
 'action of the union region is wielding',
 'action of the union region is zipping']